plugins: &plugins
  ecr#v1.1.4:
    login: true
  unbounce/aws-assume-role#v0.2.0: {}
  unbounce/aws-ssm#v1.0.0:
    parameters:
      AWS_ASSUME_ROLE_ARN: /integration/paulos-kube-test/BuildRoleArn

steps:
  - label: Build
    command: |
      docker build . -t paulos-kube-test:${BUILDKITE_COMMIT}
      docker tag paulos-kube-test:${BUILDKITE_COMMIT} 894790724410.dkr.ecr.us-west-2.amazonaws.com/paulos-kube-test:${BUILDKITE_COMMIT}
      docker push 894790724410.dkr.ecr.us-west-2.amazonaws.com/paulos-kube-test
    agents:
      queue: sandbox
    branches: "!master"
    plugins: *plugins

  - label: Build
    command: |
      docker build . -t paulos-kube-test:${BUILDKITE_TAG}
      docker tag paulos-kube-test:${BUILDKITE_TAG} 894790724410.dkr.ecr.us-west-2.amazonaws.com/paulos-kube-test:${BUILDKITE_TAG}
      docker push 894790724410.dkr.ecr.us-west-2.amazonaws.com/paulos-kube-test
    agents:
      queue: qa
    branches: "master"
    plugins: *plugins
