plugins: &plugins
  unbounce/aws-assume-role#v0.2.0: {}
  unbounce/aws-ssm#v1.0.0:
    parameters:
      AWS_ASSUME_ROLE_ARN: /integration/paulos-kube-test/BuildRoleArn

steps:
  - label: Build Staging
    command: |
      docker build . -t 894790724410.dkr.ecr.us-west-2.amazonaws.com/paulos-kube-test:${BUILDKITE_COMMIT}
      docker push 894790724410.dkr.ecr.us-west-2.amazonaws.com/paulos-kube-test
    agents:
      queue: sandbox
    branches: "!master !v*"
    plugins: *plugins

  - trigger: sandbox-cluster-deploy
    label: "hello world"
    branches: "!master !v*"
    build:
      env:
        OWNER: core-tribe
        APP_NAME: paulos-kube-test
        APP_VERSION: ${BUILDKITE_COMMIT}

  - label: Build QA
    command: |
      docker build . -t 894790724410.dkr.ecr.us-west-2.amazonaws.com/paulos-kube-test:${BUILDKITE_TAG}
      docker push 894790724410.dkr.ecr.us-west-2.amazonaws.com/paulos-kube-test
    agents:
      queue: default
    branches: "v*.*.*"
    plugins: *plugins
