steps:
  - label: Build
    command: |
      docker build . -t paulos-kube-test:0.1.0
      docker tag paulos-kube-test:0.1.0 894790724410.dkr.ecr.us-west-2.amazonaws.com/paulos-kube-test:0.1.0
      docker push 894790724410.dkr.ecr.us-west-2.amazonaws.com/paulos-kube-test
    agents:
      queue: sandbox
    branches: "!master"
    plugins:
      unbounce/aws-assume-role#v0.2.0: {}
      unbounce/aws-ssm#v1.0.0:
        parameters:
          AWS_ASSUME_ROLE_ARN: /integration/paulos-kube-test/BuildRoleArn
      ecr#v1.1.4:
        login: true
