apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kube-test-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: kube-test-deployment
    spec:
      containers:
      - name: kube-test-container
        image: paulos-kube-test:0.0.1
        imagePullPolicy: Never
        ports:
        - name: hello-port
          containerPort: 3000
