apiVersion: v1
kind: Secret
metadata:
  name: sumologic
type: Opaque
data:
  collector-url: aHR0cHM6Ly9lbmRwb2ludDMuY29sbGVjdGlvbi51czIuc3Vtb2xvZ2ljLmNvbS9yZWNlaXZlci92MS9odHRwL1phVm5DNGRoYVYyTlZSRThZRjczZTJra05wZHpISHdHQlhEWldyYy1tbkZjVkpSVjF0U2JYaUNaOEN6Yld5ZGNIUkRqQ0JFQWp4YmtoNFg1TWkzSE1ybWRCdHVGMDJhWTdoUUlrWGp1QnF3YXEybTFOM0YzbEE9PQo=
